CREATE TABLE USERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(64) NOT NULL,
    CPF VARCHAR(20) NOT NULL,
    CNPJ VARCHAR(20),
    ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE TABLE PRODUTOS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    QUANTIDADE INTEGER,
    PRECO DECIMAL(4,2),
    ACTIVE BOOLEAN DEFAULT TRUE,
    user_id INTEGER,
    FOREIGN KEY (user_id) REFERENCES USERS(ID)
);

CREATE TABLE VENDAS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    QUANTIDADE INTEGER NOT NULL,
    PRECO DECIMAL(4,2) NOT NULL,
    user_id INTEGER,
    product_id INTEGER,
    FOREIGN KEY (user_id) REFERENCES USERS(ID),
    FOREIGN KEY (product_id) REFERENCES PRODUTOS(ID)
);